In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("data1.csv")

In [ ]:
df.head()

   Student_Id   Age   Gender  StudyHours  Attendance  Marks Result
0           1   18.0  Female         5.5        65.0     70   PASS
1           2   18.0    Male         9.0        78.0     98   PASS
2           3   18.0  Female         9.5        80.0     92   PASS
3           4   19.0    Male         7.5        75.0     90   PASS
4           5   18.0    Male         4.0        80.0     35   FAIL

In [ ]:
df.tail()

   Student_Id   Age   Gender  StudyHours  Attendance  Marks Result
4           5   18.0    Male         4.0        80.0     35   FAIL
5           6    NaN    Male         5.0         NaN     85   PASS
6           7    NaN  Female         6.7        89.0     90   PASS
7           9   18.0    Male         2.2        39.0     39   FAIL
8          10   19.0  Female         2.2        76.0     24   FAIL

In [ ]:
df.shape

(9, 7)

In [ ]:
df.columns

Index(['Student_Id', ' Age ', 'Gender', 'StudyHours', 'Attendance', 'Marks',
       'Result'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip()

Now that the column names are clean, we can correctly fill the missing values in the 'Age' column.

In [ ]:
df.dtypes

Student_Id      int64
 Age          float64
Gender         object
StudyHours    float64
Attendance    float64
Marks           int64
Result         object
dtype: object

In [ ]:
df.isnull()

   Student_Id   Age   Gender  StudyHours  Attendance  Marks  Result
0       False  False   False       False       False  False   False
1       False  False   False       False       False  False   False
2       False  False   False       False       False  False   False
3       False  False   False       False       False  False   False
4       False  False   False       False       False  False   False
5       False   True   False       False        True  False   False
6       False   True   False       False       False  False   False
7       False  False   False       False       False  False   False
8       False  False   False       False       False  False   False

In [ ]:
df["Age"].fillna(df["Age"].mode()[0],inplace=True)

/tmp/ipykernel_4503/1794443001.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mode()[0],inplace=True)

In [ ]:
print(df)

   Student_Id   Age  Gender  StudyHours  Attendance  Marks Result
0           1  18.0  Female         5.5        65.0     70   PASS
1           2  18.0    Male         9.0        78.0     98   PASS
2           3  18.0  Female         9.5        80.0     92   PASS
3           4  19.0    Male         7.5        75.0     90   PASS
4           5  18.0    Male         4.0        80.0     35   FAIL
5           6  18.0    Male         5.0         NaN     85   PASS
6           7  18.0  Female         6.7        89.0     90   PASS
7           9  18.0    Male         2.2        39.0     39   FAIL
8          10  19.0  Female         2.2        76.0     24   FAIL

In [ ]:
df.isnull()

   Student_Id    Age  Gender  StudyHours  Attendance  Marks  Result
0       False  False   False       False       False  False   False
1       False  False   False       False       False  False   False
2       False  False   False       False       False  False   False
3       False  False   False       False       False  False   False
4       False  False   False       False       False  False   False
5       False  False   False       False        True  False   False
6       False  False   False       False       False  False   False
7       False  False   False       False       False  False   False
8       False  False   False       False       False  False   False

In [ ]:
df.describe()

       Student_Id        Age  StudyHours  Attendance      Marks
count    9.000000   9.000000    9.000000    8.000000   9.000000
mean     5.222222  18.222222    5.733333   72.750000  69.222222
std      3.073181   0.440959    2.680485   15.172814  28.700077
min      1.000000  18.000000    2.200000   39.000000  24.000000
25%      3.000000  18.000000    4.000000   72.500000  39.000000
50%      5.000000  18.000000    5.500000   77.000000  85.000000
75%      7.000000  18.000000    7.500000   80.000000  90.000000
max     10.000000  19.000000    9.500000   89.000000  98.000000

In [ ]:
new_date={
    'Student_Id':[10,11],
    'Age':[20,20],
    'Gender':['Male','Female'],
    'StudyHours':[12,11],
    'Attendance':[70,71],
    'Marks':[95,96],
    'Result':['PASS',],

}

n=pd.DateFrame(new_date)
m.to_csv(/content/data1.csv,mode='a',index=False,Header=false)